BONITO_INIT=$1
TRAINING_DIRECTORY=$2
CONFIG=$3
DATA_ROOT=$4
BACTERIA=$5
NAME_TEMPLATE=${$6:-bac8_0.05_test}

for CUR_BAC in $BACTERIA
do
  echo "Training model without $CUR_BAC"
  python3 $BONITO_INIT train $TRAINING_DIRECTORY $CONFIG --directory $DATA_ROOT/$NAME_TEMPLATE$CUR_BAC --amp 128 1000000
done
